---
- name: Config Elk VM
  hosts: Elk
  become: true
  tasks:

    - name: Max Map Count Set
        name: va.max_map_count
        value: '262144'
        sysctl_set: yes
        state: present
        reload: yes

    - name: docker.io
      apt:
        force_apt_get: yes
        update_cache: yes
        name: docker.io
        state: present

    - name: Install pip3
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    - name: Install Python Docker Module
      pip:
        name: docker
        state: present

    - name: download and launch a docker web container
      docker_container:
        name: sebp
        image: elk/sebp
        state: started
        restart_policy: always
        published_ports:
         -5601:5601
         -9200:9200
         -5044:5044

    - name: Enable docker service
      systemd:
        name: docker
        enabled: yes
 
